### ISSUE TITLE
AI training

### ISSUE THREAD

**Issue by thegrimbee** [thegrimbee/horus#3]
Training for the AI to analyse the terms of services

**Comment by thegrimbee** [comment]
:)))))))))

**Comment by datletu** [comment]
Label out terms and services as sus or not sus into a csv file.

**Comment by thegrimbee** [comment]
probably gonna stick with textblob model since it's light and offline, managed to make it much more accurate with a custom scoring system

**Comment by thegrimbee** [comment]
any more training and the model would be too heavy, current state can be seen in ai-development branch in horus-server
